---
Name: focuspointcrop
After: 'focuspoint'
---
SilverStripe\Assets\Image:
  extensions:
    - Restruct\SilverStripe\ImageCropper\ImageCropperExtension

JonoM\FocusPoint\Forms\FocusPointField:
  max_width: 400
  max_height: 300

SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Restruct\SilverStripe\ImageCropper\ImageCropperFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'moritz-sauer-13/silverstripe-focuspointcropper: client/dist/styles/sscropper.css'
  extra_requirements_javascript:
    - 'moritz-sauer-13/silverstripe-focuspointcropper: client/dist/js/sscropper.js'
